[build]
# Build the app from the frontend/ directory
base = "frontend"
publish = "dist"
# Ensure a clean install before build (uses package-lock)
command = "npm ci && npm run build"

[build.environment]
# Pin a Node version compatible with your local setup & Vite
NODE_VERSION = "20.19.0"

# React Router / SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
