# netlify.toml (root of the repo)
[build]
  base    = "frontend"
  command = "npm ci && npm run build"
  publish = "dist"

# React Router / SPA fallback (client-side routes)
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
