# Generated by Django 5.2.6 on 2025-09-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gameentry_playsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
