# Generated by Django 5.2.6 on 2025-09-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_paused_to_played'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameentry',
            options={'verbose_name': 'Game entry', 'verbose_name_plural': 'Game entries'},
        ),
        migrations.AlterModelOptions(
            name='playsession',
            options={'verbose_name': 'Play session', 'verbose_name_plural': 'Play sessions'},
        ),
        migrations.AlterField(
            model_name='gameentry',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'Planning'), ('PLAYING', 'Playing'), ('PLAYED', 'Played'), ('DROPPED', 'Dropped'), ('COMPLETED', 'Completed')], default='PLANNING', max_length=10),
        ),
    ]
