# Generated by Django 5.2.6 on 2025-09-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_wishlist_and_merge_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(blank=True, choices=[('WISHLIST', 'Wishlist'), ('PLAYING', 'Playing'), ('PLAYED', 'Played'), ('DROPPED', 'Dropped')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gameentry',
            name='status',
            field=models.CharField(choices=[('WISHLIST', 'Wishlist'), ('PLAYING', 'Playing'), ('PLAYED', 'Played'), ('DROPPED', 'Dropped')], default='WISHLIST', max_length=10),
        ),
    ]
