# Generated by Django 5.2.6 on 2025-09-13 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_activity_status_alter_gameentry_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='rawg_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='gameentry',
            index=models.Index(fields=['user', 'game'], name='core_gameen_user_id_8d7971_idx'),
        ),
        migrations.AddIndex(
            model_name='gameentry',
            index=models.Index(fields=['user', 'status'], name='core_gameen_user_id_ed5478_idx'),
        ),
        migrations.AddIndex(
            model_name='gameentry',
            index=models.Index(fields=['updated_at'], name='core_gameen_updated_a14c87_idx'),
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='games', to='core.genre'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['title'], name='core_game_title_f0d5e2_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['release_year'], name='core_game_release_d558fa_idx'),
        ),
    ]
